# Generated by Django 4.0.3 on 2022-04-08 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BowDamageTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bow_type",
                    models.CharField(
                        choices=[
                            ("ASYM", "Asymmetric"),
                            ("LONG", "Long"),
                            ("SHORT", "Short"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "range",
                    models.FloatField(
                        help_text="The range from the bow's tooltip",
                        validators=[
                            django.core.validators.MinValueValidator(0.1)
                        ],
                    ),
                ),
                (
                    "durability_current",
                    models.FloatField(
                        help_text="Remaining durability before starting the trial",
                        validators=[
                            django.core.validators.MinValueValidator(0.1)
                        ],
                    ),
                ),
                (
                    "durability_max",
                    models.FloatField(
                        help_text="Maximum durability of the bow (second number in tooltip)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1)
                        ],
                    ),
                ),
                (
                    "mean_damage",
                    models.FloatField(
                        help_text="The average damage per shot to the target dummy's head",
                        validators=[
                            django.core.validators.MinValueValidator(0.0)
                        ],
                    ),
                ),
            ],
        ),
    ]
