# Generated by Django 4.0.3 on 2022-04-08 21:23

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bowdamagetrial",
            name="damage_log",
            field=models.TextField(
                default="",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("(\\d+)(?:\\s?){10}"),
                        message="Enter just the 10 numbers, 1 number per line",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
