# Generated by Django 4.0.3 on 2022-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_bowdamagetrial_durability_max"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bowdamagepredictor",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="bowdamagetrial",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="bowdamagepredictor",
            name="queryset_filter",
            field=models.JSONField(
                default=dict,
                help_text="The data used to fit the predictive model will be `target_model.objects.filter(**queryset_filter).values()`",
            ),
        ),
    ]
