version: "3.7"
# Compose file for dev server only, hidden away in this directory
#  because otherwise Beanstalk will try to run it in production
services:
  api:
    tty: true
    build:
      context: ..
      dockerfile: dev/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ..:/mo2info:cached
      - .pgpass:/mo2info/.pgpass

  postgres:
    image: postgres:14.2
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_PASSWORD=localdevpassword
